/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_globalkey_NativeKeyboardHook */

#ifndef _Included_com_example_globalkey_NativeKeyboardHook
#define _Included_com_example_globalkey_NativeKeyboardHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_globalkey_NativeKeyboardHook
 * Method:    startHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_globalkey_NativeKeyboardHook_startHook
  (JNIEnv *, jobject);

/*
 * Class:     com_example_globalkey_NativeKeyboardHook
 * Method:    getDroppedEventsNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_globalkey_NativeKeyboardHook_getDroppedEventsNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
